### ISSUE TITLE
Upgrading to Full Version of Attest UX

### ISSUE THREAD

**Issue by chriscm2006** [dequelabs/Deque-University-for-iOS#40]
We should change the "Upgrade to Full Version" path. Instead of using the weird "Library Version" Environment variable, we should just add a 

DEQUE_FULL_API_KEY 

Environment variable. 

- When this is set, we utilize this API Key to fetch from the full repo.
- When the ANON API key is set, we fetch from the free trial repo.
- When neither is set, we share an error messages stating such.

### Tasks
- [x] Update Bash Scripts to reflect the above process
- [x] Update the WIKI to document the above changes
- [x] Add Deque Help Desk call out for this change on this issue.
